parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/nginx-logs
- crowdsecurity/http-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/adrianrudnik/matrix-wellknown-probing.yaml
postoverflows:
- ""
log_file: matrix-wellknown-probing.log
log_type: nginx
ignore_parsers: true
